title: First GitHub Site
author: Gus Vettleson
email: mrvettleson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Not much to see here.  These aren't the droids you are looking for.

# social links
twitter_username: N/A
github_username:  mrvettleson

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
